language: php

services:
  - couchdb

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
    allow_failures:
        - php: 7.0

before_script:
  - curl -X PUT localhost:5984/doctrine_test_database
  - composer install
